import React from 'react';
import { useQuery } from '@tanstack/react-query';
import { Building2, CalendarDays, ClipboardCheck, Ticket, Users } from 'lucide-react';
import { Link } from 'react-router-dom';
import { dashboardService } from '../../services/dashboard.service.js';
import { MetricCard } from '../../components/common/MetricCard.jsx';
import { Card, CardContent, CardHeader, CardTitle } from '../../components/ui/card.jsx';
import { Button } from '../../components/ui/button.jsx';

export const AdminDashboardPage = () => {
  const { data, isLoading } = useQuery({ queryKey: ['dashboard', 'admin'], queryFn: dashboardService.admin });
  if (isLoading) return <p className="py-12 text-center text-muted-foreground">Loading platform dashboard…</p>;
  const { metrics = {}, pending_colleges: pendingColleges = [], pending_events: pendingEvents = [] } = data?.data || {};
  return <div className="max-w-7xl mx-auto py-8 space-y-7"><div><h1 className="text-3xl font-extrabold">Platform dashboard</h1><p className="text-sm text-muted-foreground">A live overview of Festo growth, moderation queues, and attendance.</p></div><div className="grid sm:grid-cols-2 lg:grid-cols-4 gap-4"><MetricCard label="Users" value={metrics.total_users} icon={Users} /><MetricCard label="Verified colleges" value={metrics.verified_colleges} icon={Building2} tone="emerald" /><MetricCard label="Registrations" value={metrics.registrations} icon={Ticket} tone="cyan" /><MetricCard label="Gate check-ins" value={metrics.check_ins} icon={ClipboardCheck} tone="amber" /></div><div className="grid lg:grid-cols-2 gap-6"><Card><CardHeader className="flex flex-row items-center justify-between"><CardTitle className="text-lg">College applications ({metrics.pending_colleges || 0})</CardTitle><Button asChild size="sm" variant="outline"><Link to="/admin/colleges">Review all</Link></Button></CardHeader><CardContent className="space-y-3">{pendingColleges.length === 0 ? <p className="text-sm text-muted-foreground">No pending college applications.</p> : pendingColleges.map((college) => <div key={college.id} className="text-sm"><p className="font-semibold">{college.name}</p><p className="text-xs text-muted-foreground">{college.location || 'Location not provided'} · submitted {new Date(college.created_at).toLocaleDateString()}</p></div>)}</CardContent></Card><Card><CardHeader className="flex flex-row items-center justify-between"><CardTitle className="text-lg">Event approvals ({metrics.pending_events || 0})</CardTitle><Button asChild size="sm" variant="outline"><Link to="/admin/events">Review all</Link></Button></CardHeader><CardContent className="space-y-3">{pendingEvents.length === 0 ? <p className="text-sm text-muted-foreground">No pending event submissions.</p> : pendingEvents.map((event) => <div key={event.id} className="text-sm"><p className="font-semibold">{event.title}</p><p className="text-xs text-muted-foreground">{event.college_name} · {new Date(event.start_date).toLocaleDateString()}</p></div>)}</CardContent></Card></div><Card><CardContent className="p-5 flex flex-wrap gap-6 text-sm text-muted-foreground"><span><CalendarDays className="w-4 h-4 inline mr-1 text-purple-400" />{metrics.published_events || 0} published events</span><span>{metrics.students || 0} student accounts</span></CardContent></Card></div>;
};
